PLANNER-2588: Add integration test for optaplanner-quarkus-benchmark
Native test fails due to AWT:

Error: Classes that should be initialized at run time got initialized during image building:
 sun.font.AttributeValues the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.AttributeValues got initialized use --trace-class-initialization=sun.font.AttributeValues
sun.java2d.SunGraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.java2d.SunGraphicsEnvironment got initialized use --trace-class-initialization=sun.java2d.SunGraphicsEnvironment
sun.awt.SunHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunHints got initialized use --trace-class-initialization=sun.awt.SunHints
java.awt.Font the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Font got initialized use --trace-class-initialization=java.awt.Font
sun.awt.X11.XToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11.XToolkit got initialized use --trace-class-initialization=sun.awt.X11.XToolkit
sun.awt.HeadlessToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.HeadlessToolkit got initialized use --trace-class-initialization=sun.awt.HeadlessToolkit
sun.awt.AWTAccessor the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.AWTAccessor got initialized use --trace-class-initialization=sun.awt.AWTAccessor
sun.awt.SunToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunToolkit got initialized use --trace-class-initialization=sun.awt.SunToolkit
java.awt.Component the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Component got initialized use --trace-class-initialization=java.awt.Component
sun.awt.util.PerformanceLogger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.util.PerformanceLogger got initialized use --trace-class-initialization=sun.awt.util.PerformanceLogger
java.awt.Toolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit got initialized use --trace-class-initialization=java.awt.Toolkit
java.awt.Color the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Color got initialized use --trace-class-initialization=java.awt.Color
sun.awt.X11GraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11GraphicsEnvironment got initialized use --trace-class-initialization=sun.awt.X11GraphicsEnvironment
sun.font.EAttribute the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.EAttribute got initialized use --trace-class-initialization=sun.font.EAttribute
java.awt.Toolkit$DesktopPropertyChangeSupport the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit$DesktopPropertyChangeSupport got initialized use --trace-class-initialization=java.awt.Toolkit$DesktopPropertyChangeSupport
java.awt.GraphicsEnvironment$LocalGE the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.GraphicsEnvironment$LocalGE got initialized use --trace-class-initialization=java.awt.GraphicsEnvironment$LocalGE
sun.awt.SunDisplayChanger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunDisplayChanger got initialized use --trace-class-initialization=sun.awt.SunDisplayChanger
sun.awt.UNIXToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.UNIXToolkit got initialized use --trace-class-initialization=sun.awt.UNIXToolkit
java.awt.RenderingHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.RenderingHints got initialized use --trace-class-initialization=java.awt.RenderingHints

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 sun.font.AttributeValues the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.AttributeValues got initialized use --trace-class-initialization=sun.font.AttributeValues
sun.java2d.SunGraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.java2d.SunGraphicsEnvironment got initialized use --trace-class-initialization=sun.java2d.SunGraphicsEnvironment
sun.awt.SunHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunHints got initialized use --trace-class-initialization=sun.awt.SunHints
java.awt.Font the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Font got initialized use --trace-class-initialization=java.awt.Font
sun.awt.X11.XToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11.XToolkit got initialized use --trace-class-initialization=sun.awt.X11.XToolkit
sun.awt.HeadlessToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.HeadlessToolkit got initialized use --trace-class-initialization=sun.awt.HeadlessToolkit
sun.awt.AWTAccessor the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.AWTAccessor got initialized use --trace-class-initialization=sun.awt.AWTAccessor
sun.awt.SunToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunToolkit got initialized use --trace-class-initialization=sun.awt.SunToolkit
java.awt.Component the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Component got initialized use --trace-class-initialization=java.awt.Component
sun.awt.util.PerformanceLogger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.util.PerformanceLogger got initialized use --trace-class-initialization=sun.awt.util.PerformanceLogger
java.awt.Toolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit got initialized use --trace-class-initialization=java.awt.Toolkit
java.awt.Color the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Color got initialized use --trace-class-initialization=java.awt.Color
sun.awt.X11GraphicsEnvironment the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.X11GraphicsEnvironment got initialized use --trace-class-initialization=sun.awt.X11GraphicsEnvironment
sun.font.EAttribute the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.font.EAttribute got initialized use --trace-class-initialization=sun.font.EAttribute
java.awt.Toolkit$DesktopPropertyChangeSupport the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.Toolkit$DesktopPropertyChangeSupport got initialized use --trace-class-initialization=java.awt.Toolkit$DesktopPropertyChangeSupport
java.awt.GraphicsEnvironment$LocalGE the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.GraphicsEnvironment$LocalGE got initialized use --trace-class-initialization=java.awt.GraphicsEnvironment$LocalGE
sun.awt.SunDisplayChanger the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.SunDisplayChanger got initialized use --trace-class-initialization=sun.awt.SunDisplayChanger
sun.awt.UNIXToolkit the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why sun.awt.UNIXToolkit got initialized use --trace-class-initialization=sun.awt.UNIXToolkit
java.awt.RenderingHints the class was requested to be initialized at run time (Quarkus run time init for AWT). To see why java.awt.RenderingHints got initialized use --trace-class-initialization=java.awt.RenderingHints